a = input('Digite algo ')
print('O tipo primitivo desse valor é ',type(a))
print('So tem espaço :', a.isspace())
print('É um numero : ', a.isnumeric())
print('É alfabetico : ', a.isalpha())
print('É alfanumerico :',a.isalnum())
print('Esta em maiuscula : ',a.islower())
print('Esta capitalizada : ', a.istitle())
