numero = int(input('Digite um numero para tabuada : '))
print('---------TABUADA-----------')
print('{} X {}'.format(numero, numero * 1))
print('{} X {}'.format(numero, numero * 2))
print('{} x {}'.format(numero,numero * 3))
print('{} x {}'.format(numero,numero * 4))
print('{} x {}'.format(numero,numero * 5))
print('{} x {}'.format(numero, numero * 6))
print('{} x {}'.format(numero, numero * 7))
print('{} X {}'.format(numero,numero * 8))
print('{} x {}'.format(numero, numero * 9))
print('{} x {}'.format(numero,numero *10))
